### ISSUE TITLE
Singletrack - do we need it?

### ISSUE THREAD

**Issue by YaroShkvorets** [osmottawa/OSM-Bike-Ottawa-Tagging-Guide#14]
Seems confusing.
Can be tagged as highway=path with certain surface and smoothness.

**Comment by heatshear** [comment]
I like highway=path, with smoothness and surface. Possibly also width = 1

Even though it basically is redundant, I'd still keep the category. My reasoning is so that people reading our guide know how to tag singletrack. Otherwise, I'm a bit worried that it might sometimes get tagged as a desire line, since they share many characteristics, with the exception that a desire line should probably be formalized into an upgraded path one day. I see the desire line category as a way to mine the map for path network needs.

**Comment by YaroShkvorets** [comment]
Ah ok. I thought you meant to tag it with some specific tags. Nevermind then.
