### ISSUE TITLE
The tagging guide doesn't make sense to me with the reformatting

### ISSUE THREAD

**Issue by heatshear** [osmottawa/OSM-Bike-Ottawa-Tagging-Guide#31]
Those recent format changes don't work, IMO. I was liking how we had sections for things you'd ride on, obstacles you'd encounter, etc. Now it seems all split up... things you'd ride on are showing up all over the place (it starts with MUPs, for example, then there's some stuff about parking, signs, obstacles, and then we're back to another thing you'd ride on - a paved shoulder).  Is there some logic to this flow that I'm not getting? I'd really like to see this put back how it was, or maybe I'm just catching this midway through some re-arranging?

**Comment by DenisCarriere** [comment]
Humm.. don't think anything was changed, the groups are the same.

We can re-organize the items by re-ordering them in the YAML files.

We definitely need to "group" them in a logical way, it does feel a bit all over the place

👍

**Comment by heatshear** [comment]
Weird. I can send you a screen shot of what I'm seeing - the photos are huge now, and the tables are all gone - everything has its own heading.

**Comment by heatshear** [comment]
![image](https://user-images.githubusercontent.com/30479453/32529863-e387143e-c408-11e7-8da5-cce9af74218a.png)

**Comment by DenisCarriere** [comment]
Yea the photos are bigger, we can always change that back...

**Comment by heatshear** [comment]
It seems like everything has been re-grouped by tag type?

**Comment by DenisCarriere** [comment]
The reason why I changed it was because it was hard to reference a particular item since the groups were so big... but if it's too complicated now I can change it back.

**Comment by heatshear** [comment]
Yeah, I don't like the big photos.... too much scrolling

**Comment by heatshear** [comment]
I think it's too complicated, at least for me. I don't think in tag types, I think about the infrastructure first. It made sense to me to have "all the things you'd ride on" as a single table, for example. Within the table, they were ordered roughly by degree of separation from traffic. I'd find the thing I'm trying to tag, then read the table to find how to tag it.

**Comment by DenisCarriere** [comment]
Ok I switched it back, my bad 🤦‍♂️ 

![image](https://user-images.githubusercontent.com/550895/32530013-a4cf9ee0-c409-11e7-871e-b0309c9d0fab.png)

**Comment by DenisCarriere** [comment]
I did add a few more stuff in the Table of Contents, I separated the `shoulder` features to their own group.

![image](https://user-images.githubusercontent.com/550895/32530057-dd8bb4ee-c409-11e7-89e1-17abda340b36.png)

**Comment by heatshear** [comment]
Thanks, I can navigate again! But, I don;t get why shoulders would be a separate category for a bike tagging guide - I'd expect to find them along with everything else I ride on.

**Comment by heatshear** [comment]
I'd prefer them along with everything else you ride on (functionally, they are bike lanes and cycletracks), but I could live with a separate table as long as it was immediately under the first table, instead of after Smoothness?

**Comment by DenisCarriere** [comment]
Feel free re-organize the items, I just felt that the HIghway group was getting too big and the issue is when you attempt to make links to the Guide, you can't reference a single item in the Table, you have to reference the header (ex: Highway/Smoothness).

So in the Tasking Manager, I'm referencing the Ottawa OSM Guide to the specific tags:

- [`highway`](https://github.com/osmottawa/OSM-Bike-Ottawa-Tagging-Guide#highway)
- [`smoothness`](https://github.com/osmottawa/OSM-Bike-Ottawa-Tagging-Guide#smoothness)
- [`parking:lane:left/right/both`](https://github.com/osmottawa/OSM-Bike-Ottawa-Tagging-Guide#parking)
- [`shoulder:left/right/both`](https://github.com/osmottawa/OSM-Bike-Ottawa-Tagging-Guide#Shoulder)
- [`cycleway`](https://github.com/osmottawa/OSM-Bike-Ottawa-Tagging-Guide#bi-directional-protected-cycletrack)
- [`cycleway:buffer`](https://github.com/osmottawa/OSM-Bike-Ottawa-Tagging-Guide#buffered-bike-lane)

![image](https://user-images.githubusercontent.com/550895/32530286-365b798c-c40b-11e7-9ea0-afecf56027d6.png)

http://tasks.osmcanada.ca/project/84

If all of those links just point to the same Header (ex: Highway) then it wouldn't be very useful as a link.

**Comment by heatshear** [comment]
Yeah, that makes sense. I'd love it if there was a way to still have that huge table since it's comprehensive, but with some hidden navigation bookmarks for the tasking. Sorry to not be actually helpful. No matter what, it's gong to be fun tomorrow.
